version: "3"

services:
  app:
    build: docker/dev
    container_name: "protidhoni"
    ports:
      - "8000:80"
      - "5173:5173" ## js dev
      - "8080:8080" ## reverb
    volumes:
      - .:/app
